### ISSUE TITLE
Ignore trailing whitespaces in comments (CheckStyle)

### ISSUE THREAD

**Issue by noxone** [lars-sh/parent#2]

**Comment by lars-sh** [comment]
I tried to reproduce what you described me offline, but were not able to. Can you give me some example code that your Save Actions do not format correctly.

I tried the following and all trailing whitespaces are gone jut after saving.
```
/**
 * Some text A[WHITESPACE]
 * [WHITESPACE]
 * <p>[WHITESPACE]
 * Some text B[WHITESPACE]
 */
```

**Comment by noxone** [comment]
No, I cannot. 
When formatting files it’s ok. But from time to time a saved file obviously contains trailing whitespaces in comments. Editing that file again (and this running the save actions) solves then problem. 
Nevertheless imo a trailing whitespace in a comment should not prevent a file from compiling. What would be the reason?

Oh, just one thing: every time the trailing whitespace problem occurred it looked like this:
/**
 * Some text
 *[blank]
 * @something
 */

**Comment by lars-sh** [comment]
Actually this seems to be an Eclipse side problem that cannot be handled by us. This POM is intended to make sure (as best as it can) that running Eclipse code clean up won't create changes. Therefore I'd like to leave the behaviour as is.
